import 'package:drift/drift.dart';
import 'package:stairs/db/database.dart';

final defaultCountryCodeList = [
  const MCountryCodeCompanion(
    code: Value(1),
    name: Value('Afghanistan'),
    japaneseName: Value('アフガニスタン'),
  ),
  const MCountryCodeCompanion(
    code: Value(2),
    name: Value('Albania'),
    japaneseName: Value('アルバニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(3),
    name: Value('Algeria'),
    japaneseName: Value('アルジェリア'),
  ),
  const MCountryCodeCompanion(
    code: Value(4),
    name: Value('Andorra'),
    japaneseName: Value('アンドラ'),
  ),
  const MCountryCodeCompanion(
    code: Value(5),
    name: Value('Angola'),
    japaneseName: Value('アンゴラ'),
  ),
  const MCountryCodeCompanion(
    code: Value(6),
    name: Value('Antigua and Barbuda'),
    japaneseName: Value('アンティグア・バーブーダ'),
  ),
  const MCountryCodeCompanion(
    code: Value(7),
    name: Value('Argentina'),
    japaneseName: Value('アルゼンチン'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(8),
    name: Value('Armenia'),
    japaneseName: Value('アルメニア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(9),
    name: Value('Australia'),
    japaneseName: Value('オーストラリア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(10),
    name: Value('Austria'),
    japaneseName: Value('オーストリア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(11),
    name: Value('Azerbaijan'),
    japaneseName: Value('アゼルバイジャン'),
  ),
  const MCountryCodeCompanion(
    code: Value(12),
    name: Value('Bahamas'),
    japaneseName: Value('バハマ'),
  ),
  const MCountryCodeCompanion(
    code: Value(13),
    name: Value('Bahrain'),
    japaneseName: Value('バーレーン'),
  ),
  const MCountryCodeCompanion(
    code: Value(14),
    name: Value('Bangladesh'),
    japaneseName: Value('バングラデシュ'),
  ),
  const MCountryCodeCompanion(
    code: Value(15),
    name: Value('Barbados'),
    japaneseName: Value('バルバドス'),
  ),
  const MCountryCodeCompanion(
    code: Value(16),
    name: Value('Belarus'),
    japaneseName: Value('ベラルーシ'),
  ),
  const MCountryCodeCompanion(
    code: Value(17),
    name: Value('Belgium'),
    japaneseName: Value('ベルギー'),
  ),
  const MCountryCodeCompanion(
    code: Value(18),
    name: Value('Belize'),
    japaneseName: Value('ベリーズ'),
  ),
  const MCountryCodeCompanion(
    code: Value(19),
    name: Value('Benin'),
    japaneseName: Value('ベナン'),
  ),
  const MCountryCodeCompanion(
    code: Value(20),
    name: Value('Bhutan'),
    japaneseName: Value('ブータン'),
  ),
  const MCountryCodeCompanion(
    code: Value(21),
    name: Value('Bolivia'),
    japaneseName: Value('ボリビア'),
  ),
  const MCountryCodeCompanion(
    code: Value(22),
    name: Value('Bosnia and Herzegovina'),
    japaneseName: Value('ボスニア・ヘルツェゴビナ'),
  ),
  const MCountryCodeCompanion(
    code: Value(23),
    name: Value('Botswana'),
    japaneseName: Value('ボツワナ'),
  ),
  const MCountryCodeCompanion(
    code: Value(24),
    name: Value('Brazil'),
    japaneseName: Value('ブラジル'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(25),
    name: Value('Brunei'),
    japaneseName: Value('ブルネイ'),
  ),
  const MCountryCodeCompanion(
    code: Value(26),
    name: Value('Bulgaria'),
    japaneseName: Value('ブルガリア'),
  ),
  const MCountryCodeCompanion(
    code: Value(27),
    name: Value('Burkina Faso'),
    japaneseName: Value('ブルキナファソ'),
  ),
  const MCountryCodeCompanion(
    code: Value(28),
    name: Value('Burundi'),
    japaneseName: Value('ブルンジ'),
  ),
  const MCountryCodeCompanion(
    code: Value(29),
    name: Value('Cabo Verde'),
    japaneseName: Value('カーボベルデ'),
  ),
  const MCountryCodeCompanion(
    code: Value(30),
    name: Value('Cambodia'),
    japaneseName: Value('カンボジア'),
  ),
  const MCountryCodeCompanion(
    code: Value(31),
    name: Value('Cameroon'),
    japaneseName: Value('カメルーン'),
  ),
  const MCountryCodeCompanion(
    code: Value(32),
    name: Value('Canada'),
    japaneseName: Value('カナダ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(33),
    name: Value('Central African Republic'),
    japaneseName: Value('中央アフリカ共和国'),
  ),
  const MCountryCodeCompanion(
    code: Value(34),
    name: Value('Chad'),
    japaneseName: Value('チャド'),
  ),
  const MCountryCodeCompanion(
    code: Value(35),
    name: Value('Chile'),
    japaneseName: Value('チリ'),
  ),
  const MCountryCodeCompanion(
    code: Value(36),
    name: Value('China'),
    japaneseName: Value('中国'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(37),
    name: Value('Colombia'),
    japaneseName: Value('コロンビア'),
  ),
  const MCountryCodeCompanion(
    code: Value(38),
    name: Value('Comoros'),
    japaneseName: Value('コモロ'),
  ),
  const MCountryCodeCompanion(
    code: Value(39),
    name: Value('Congo'),
    japaneseName: Value('コンゴ'),
  ),
  const MCountryCodeCompanion(
    code: Value(40),
    name: Value('Costa Rica'),
    japaneseName: Value('コスタリカ'),
  ),
  const MCountryCodeCompanion(
    code: Value(41),
    name: Value('Croatia'),
    japaneseName: Value('クロアチア'),
  ),
  const MCountryCodeCompanion(
    code: Value(42),
    name: Value('Cuba'),
    japaneseName: Value('キューバ'),
  ),
  const MCountryCodeCompanion(
    code: Value(43),
    name: Value('Cyprus'),
    japaneseName: Value('キプロス'),
  ),
  const MCountryCodeCompanion(
    code: Value(44),
    name: Value('Czech Republic'),
    japaneseName: Value('チェコ'),
  ),
  const MCountryCodeCompanion(
    code: Value(45),
    name: Value('Denmark'),
    japaneseName: Value('デンマーク'),
  ),
  const MCountryCodeCompanion(
    code: Value(46),
    name: Value('Djibouti'),
    japaneseName: Value('ジブチ'),
  ),
  const MCountryCodeCompanion(
    code: Value(47),
    name: Value('Dominica'),
    japaneseName: Value('ドミニカ'),
  ),
  const MCountryCodeCompanion(
    code: Value(48),
    name: Value('Dominican Republic'),
    japaneseName: Value('ドミニカ共和国'),
  ),
  const MCountryCodeCompanion(
    code: Value(49),
    name: Value('Ecuador'),
    japaneseName: Value('エクアドル'),
  ),
  const MCountryCodeCompanion(
    code: Value(50),
    name: Value('Egypt'),
    japaneseName: Value('エジプト'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(51),
    name: Value('El Salvador'),
    japaneseName: Value('エルサルバドル'),
  ),
  const MCountryCodeCompanion(
    code: Value(52),
    name: Value('Equatorial Guinea'),
    japaneseName: Value('赤道ギニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(53),
    name: Value('Eritrea'),
    japaneseName: Value('エリトリア'),
  ),
  const MCountryCodeCompanion(
    code: Value(54),
    name: Value('Estonia'),
    japaneseName: Value('エストニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(55),
    name: Value('Eswatini'),
    japaneseName: Value('エスワティニ'),
  ),
  const MCountryCodeCompanion(
    code: Value(56),
    name: Value('Ethiopia'),
    japaneseName: Value('エチオピア'),
  ),
  const MCountryCodeCompanion(
    code: Value(57),
    name: Value('Fiji'),
    japaneseName: Value('フィジー'),
  ),
  const MCountryCodeCompanion(
    code: Value(58),
    name: Value('Finland'),
    japaneseName: Value('フィンランド'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(59),
    name: Value('France'),
    japaneseName: Value('フランス'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(60),
    name: Value('Gabon'),
    japaneseName: Value('ガボン'),
  ),
  const MCountryCodeCompanion(
    code: Value(61),
    name: Value('Gambia'),
    japaneseName: Value('ガンビア'),
  ),
  const MCountryCodeCompanion(
    code: Value(62),
    name: Value('Georgia'),
    japaneseName: Value('ジョージア'),
  ),
  const MCountryCodeCompanion(
    code: Value(63),
    name: Value('Germany'),
    japaneseName: Value('ドイツ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(64),
    name: Value('Ghana'),
    japaneseName: Value('ガーナ'),
  ),
  const MCountryCodeCompanion(
    code: Value(65),
    name: Value('Greece'),
    japaneseName: Value('ギリシャ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(66),
    name: Value('Grenada'),
    japaneseName: Value('グレナダ'),
  ),
  const MCountryCodeCompanion(
    code: Value(67),
    name: Value('Guatemala'),
    japaneseName: Value('グアテマラ'),
  ),
  const MCountryCodeCompanion(
    code: Value(68),
    name: Value('Guinea'),
    japaneseName: Value('ギニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(69),
    name: Value('Guinea-Bissau'),
    japaneseName: Value('ギニアビサウ'),
  ),
  const MCountryCodeCompanion(
    code: Value(70),
    name: Value('Guyana'),
    japaneseName: Value('ガイアナ'),
  ),
  const MCountryCodeCompanion(
    code: Value(71),
    name: Value('Haiti'),
    japaneseName: Value('ハイチ'),
  ),
  const MCountryCodeCompanion(
    code: Value(72),
    name: Value('Honduras'),
    japaneseName: Value('ホンジュラス'),
  ),
  const MCountryCodeCompanion(
    code: Value(73),
    name: Value('Hungary'),
    japaneseName: Value('ハンガリー'),
  ),
  const MCountryCodeCompanion(
    code: Value(74),
    name: Value('Iceland'),
    japaneseName: Value('アイスランド'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(75),
    name: Value('India'),
    japaneseName: Value('インド'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(76),
    name: Value('Indonesia'),
    japaneseName: Value('インドネシア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(77),
    name: Value('Iran'),
    japaneseName: Value('イラン'),
  ),
  const MCountryCodeCompanion(
    code: Value(78),
    name: Value('Iraq'),
    japaneseName: Value('イラク'),
  ),
  const MCountryCodeCompanion(
    code: Value(79),
    name: Value('Ireland'),
    japaneseName: Value('アイルランド'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(80),
    name: Value('Israel'),
    japaneseName: Value('イスラエル'),
  ),
  const MCountryCodeCompanion(
    code: Value(81),
    name: Value('Italy'),
    japaneseName: Value('イタリア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(82),
    name: Value('Jamaica'),
    japaneseName: Value('ジャマイカ'),
  ),
  const MCountryCodeCompanion(
    code: Value(83),
    name: Value('Japan'),
    japaneseName: Value('日本'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(84),
    name: Value('Jordan'),
    japaneseName: Value('ヨルダン'),
  ),
  const MCountryCodeCompanion(
    code: Value(85),
    name: Value('Kazakhstan'),
    japaneseName: Value('カザフスタン'),
  ),
  const MCountryCodeCompanion(
    code: Value(86),
    name: Value('Kenya'),
    japaneseName: Value('ケニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(87),
    name: Value('Kiribati'),
    japaneseName: Value('キリバス'),
  ),
  const MCountryCodeCompanion(
    code: Value(88),
    name: Value('Kuwait'),
    japaneseName: Value('クウェート'),
  ),
  const MCountryCodeCompanion(
    code: Value(89),
    name: Value('Kyrgyzstan'),
    japaneseName: Value('キルギス'),
  ),
  const MCountryCodeCompanion(
    code: Value(90),
    name: Value('Laos'),
    japaneseName: Value('ラオス'),
  ),
  const MCountryCodeCompanion(
    code: Value(91),
    name: Value('Latvia'),
    japaneseName: Value('ラトビア'),
  ),
  const MCountryCodeCompanion(
    code: Value(92),
    name: Value('Lebanon'),
    japaneseName: Value('レバノン'),
  ),
  const MCountryCodeCompanion(
    code: Value(93),
    name: Value('Lesotho'),
    japaneseName: Value('レソト'),
  ),
  const MCountryCodeCompanion(
    code: Value(94),
    name: Value('Liberia'),
    japaneseName: Value('リベリア'),
  ),
  const MCountryCodeCompanion(
    code: Value(95),
    name: Value('Libya'),
    japaneseName: Value('リビア'),
  ),
  const MCountryCodeCompanion(
    code: Value(96),
    name: Value('Liechtenstein'),
    japaneseName: Value('リヒテンシュタイン'),
  ),
  const MCountryCodeCompanion(
    code: Value(97),
    name: Value('Lithuania'),
    japaneseName: Value('リトアニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(98),
    name: Value('Luxembourg'),
    japaneseName: Value('ルクセンブルク'),
  ),
  const MCountryCodeCompanion(
    code: Value(99),
    name: Value('Madagascar'),
    japaneseName: Value('マダガスカル'),
  ),
  const MCountryCodeCompanion(
    code: Value(100),
    name: Value('Malawi'),
    japaneseName: Value('マラウイ'),
  ),
  const MCountryCodeCompanion(
    code: Value(101),
    name: Value('Malaysia'),
    japaneseName: Value('マレーシア'),
  ),
  const MCountryCodeCompanion(
    code: Value(102),
    name: Value('Maldives'),
    japaneseName: Value('モルディブ'),
  ),
  const MCountryCodeCompanion(
    code: Value(103),
    name: Value('Mali'),
    japaneseName: Value('マリ'),
  ),
  const MCountryCodeCompanion(
    code: Value(104),
    name: Value('Malta'),
    japaneseName: Value('マルタ'),
  ),
  const MCountryCodeCompanion(
    code: Value(105),
    name: Value('Marshall Islands'),
    japaneseName: Value('マーシャル諸島'),
  ),
  const MCountryCodeCompanion(
    code: Value(106),
    name: Value('Mauritania'),
    japaneseName: Value('モーリタニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(107),
    name: Value('Mauritius'),
    japaneseName: Value('モーリシャス'),
  ),
  const MCountryCodeCompanion(
    code: Value(108),
    name: Value('Mexico'),
    japaneseName: Value('メキシコ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(109),
    name: Value('Micronesia'),
    japaneseName: Value('ミクロネシア'),
  ),
  const MCountryCodeCompanion(
    code: Value(110),
    name: Value('Moldova'),
    japaneseName: Value('モルドバ'),
  ),
  const MCountryCodeCompanion(
    code: Value(111),
    name: Value('Monaco'),
    japaneseName: Value('モナコ'),
  ),
  const MCountryCodeCompanion(
    code: Value(112),
    name: Value('Mongolia'),
    japaneseName: Value('モンゴル'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(113),
    name: Value('Montenegro'),
    japaneseName: Value('モンテネグロ'),
  ),
  const MCountryCodeCompanion(
    code: Value(114),
    name: Value('Morocco'),
    japaneseName: Value('モロッコ'),
  ),
  const MCountryCodeCompanion(
    code: Value(115),
    name: Value('Mozambique'),
    japaneseName: Value('モザンビーク'),
  ),
  const MCountryCodeCompanion(
    code: Value(116),
    name: Value('Myanmar'),
    japaneseName: Value('ミャンマー'),
  ),
  const MCountryCodeCompanion(
    code: Value(117),
    name: Value('Namibia'),
    japaneseName: Value('ナミビア'),
  ),
  const MCountryCodeCompanion(
    code: Value(118),
    name: Value('Nauru'),
    japaneseName: Value('ナウル'),
  ),
  const MCountryCodeCompanion(
    code: Value(119),
    name: Value('Nepal'),
    japaneseName: Value('ネパール'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(120),
    name: Value('Netherlands'),
    japaneseName: Value('オランダ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(121),
    name: Value('New Zealand'),
    japaneseName: Value('ニュージーランド'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(122),
    name: Value('Nicaragua'),
    japaneseName: Value('ニカラグア'),
  ),
  const MCountryCodeCompanion(
    code: Value(123),
    name: Value('Niger'),
    japaneseName: Value('ニジェール'),
  ),
  const MCountryCodeCompanion(
    code: Value(124),
    name: Value('Nigeria'),
    japaneseName: Value('ナイジェリア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(125),
    name: Value('North Korea'),
    japaneseName: Value('北朝鮮'),
  ),
  const MCountryCodeCompanion(
    code: Value(126),
    name: Value('North Macedonia'),
    japaneseName: Value('北マケドニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(127),
    name: Value('Norway'),
    japaneseName: Value('ノルウェー'),
  ),
  const MCountryCodeCompanion(
    code: Value(128),
    name: Value('Oman'),
    japaneseName: Value('オマーン'),
  ),
  const MCountryCodeCompanion(
    code: Value(129),
    name: Value('Pakistan'),
    japaneseName: Value('パキスタン'),
  ),
  const MCountryCodeCompanion(
    code: Value(130),
    name: Value('Palau'),
    japaneseName: Value('パラオ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(131),
    name: Value('Panama'),
    japaneseName: Value('パナマ'),
  ),
  const MCountryCodeCompanion(
    code: Value(132),
    name: Value('Papua New Guinea'),
    japaneseName: Value('パプアニューギニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(133),
    name: Value('Paraguay'),
    japaneseName: Value('パラグアイ'),
  ),
  const MCountryCodeCompanion(
    code: Value(134),
    name: Value('Peru'),
    japaneseName: Value('ペルー'),
  ),
  const MCountryCodeCompanion(
    code: Value(135),
    name: Value('Philippines'),
    japaneseName: Value('フィリピン'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(136),
    name: Value('Poland'),
    japaneseName: Value('ポーランド'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(137),
    name: Value('Portugal'),
    japaneseName: Value('ポルトガル'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(138),
    name: Value('Qatar'),
    japaneseName: Value('カタール'),
  ),
  const MCountryCodeCompanion(
    code: Value(139),
    name: Value('Romania'),
    japaneseName: Value('ルーマニア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(140),
    name: Value('Russia'),
    japaneseName: Value('ロシア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(141),
    name: Value('Rwanda'),
    japaneseName: Value('ルワンダ'),
  ),
  const MCountryCodeCompanion(
    code: Value(142),
    name: Value('Saint Kitts and Nevis'),
    japaneseName: Value('セントクリストファー・ネイビス'),
  ),
  const MCountryCodeCompanion(
    code: Value(143),
    name: Value('Saint Lucia'),
    japaneseName: Value('セントルシア'),
  ),
  const MCountryCodeCompanion(
    code: Value(144),
    name: Value('Saint Vincent and the Grenadines'),
    japaneseName: Value('セントビンセントおよびグレナディーン諸島'),
  ),
  const MCountryCodeCompanion(
    code: Value(145),
    name: Value('Samoa'),
    japaneseName: Value('サモア'),
  ),
  const MCountryCodeCompanion(
    code: Value(146),
    name: Value('San Marino'),
    japaneseName: Value('サンマリノ'),
  ),
  const MCountryCodeCompanion(
    code: Value(147),
    name: Value('Sao Tome and Principe'),
    japaneseName: Value('サントメ・プリンシペ'),
  ),
  const MCountryCodeCompanion(
    code: Value(148),
    name: Value('Saudi Arabia'),
    japaneseName: Value('サウジアラビア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(149),
    name: Value('Senegal'),
    japaneseName: Value('セネガル'),
  ),
  const MCountryCodeCompanion(
    code: Value(150),
    name: Value('Serbia'),
    japaneseName: Value('セルビア'),
  ),
  const MCountryCodeCompanion(
    code: Value(151),
    name: Value('Seychelles'),
    japaneseName: Value('セーシェル'),
  ),
  const MCountryCodeCompanion(
    code: Value(152),
    name: Value('Sierra Leone'),
    japaneseName: Value('シエラレオネ'),
  ),
  const MCountryCodeCompanion(
    code: Value(153),
    name: Value('Singapore'),
    japaneseName: Value('シンガポール'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(154),
    name: Value('Slovakia'),
    japaneseName: Value('スロバキア'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(155),
    name: Value('Slovenia'),
    japaneseName: Value('スロベニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(156),
    name: Value('Solomon Islands'),
    japaneseName: Value('ソロモン諸島'),
  ),
  const MCountryCodeCompanion(
    code: Value(157),
    name: Value('Somalia'),
    japaneseName: Value('ソマリア'),
  ),
  const MCountryCodeCompanion(
    code: Value(157),
    name: Value('Slovenia'),
    japaneseName: Value('スロベニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(158),
    name: Value('Solomon Islands'),
    japaneseName: Value('ソロモン諸島'),
  ),
  const MCountryCodeCompanion(
    code: Value(159),
    name: Value('Somalia'),
    japaneseName: Value('ソマリア'),
  ),
  const MCountryCodeCompanion(
    code: Value(160),
    name: Value('South Africa'),
    japaneseName: Value('南アフリカ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(161),
    name: Value('South Sudan'),
    japaneseName: Value('南スーダン'),
  ),
  const MCountryCodeCompanion(
    code: Value(162),
    name: Value('Spain'),
    japaneseName: Value('スペイン'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(163),
    name: Value('Sri Lanka'),
    japaneseName: Value('スリランカ'),
  ),
  const MCountryCodeCompanion(
    code: Value(164),
    name: Value('Sudan'),
    japaneseName: Value('スーダン'),
  ),
  const MCountryCodeCompanion(
    code: Value(165),
    name: Value('Suriname'),
    japaneseName: Value('スリナム'),
  ),
  const MCountryCodeCompanion(
    code: Value(166),
    name: Value('Sweden'),
    japaneseName: Value('スウェーデン'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(167),
    name: Value('Switzerland'),
    japaneseName: Value('スイス'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(168),
    name: Value('Syria'),
    japaneseName: Value('シリア'),
  ),
  const MCountryCodeCompanion(
    code: Value(169),
    name: Value('Tajikistan'),
    japaneseName: Value('タジキスタン'),
  ),
  const MCountryCodeCompanion(
    code: Value(170),
    name: Value('Tanzania'),
    japaneseName: Value('タンザニア'),
  ),
  const MCountryCodeCompanion(
    code: Value(171),
    name: Value('Thailand'),
    japaneseName: Value('タイ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(172),
    name: Value('Timor-Leste'),
    japaneseName: Value('東ティモール'),
  ),
  const MCountryCodeCompanion(
    code: Value(173),
    name: Value('Togo'),
    japaneseName: Value('トーゴ'),
  ),
  const MCountryCodeCompanion(
    code: Value(174),
    name: Value('Tonga'),
    japaneseName: Value('トンガ'),
  ),
  const MCountryCodeCompanion(
    code: Value(175),
    name: Value('Trinidad and Tobago'),
    japaneseName: Value('トリニダード・トバゴ'),
  ),
  const MCountryCodeCompanion(
    code: Value(176),
    name: Value('Tunisia'),
    japaneseName: Value('チュニジア'),
  ),
  const MCountryCodeCompanion(
    code: Value(177),
    name: Value('Turkey'),
    japaneseName: Value('トルコ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(178),
    name: Value('Turkmenistan'),
    japaneseName: Value('トルクメニスタン'),
  ),
  const MCountryCodeCompanion(
    code: Value(179),
    name: Value('Tuvalu'),
    japaneseName: Value('ツバル'),
  ),
  const MCountryCodeCompanion(
    code: Value(180),
    name: Value('Uganda'),
    japaneseName: Value('ウガンダ'),
  ),
  const MCountryCodeCompanion(
    code: Value(181),
    name: Value('Ukraine'),
    japaneseName: Value('ウクライナ'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(182),
    name: Value('United Arab Emirates'),
    japaneseName: Value('アラブ首長国連邦'),
  ),
  const MCountryCodeCompanion(
    code: Value(183),
    name: Value('United Kingdom'),
    japaneseName: Value('イギリス'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(184),
    name: Value('United States'),
    japaneseName: Value('アメリカ合衆国'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(185),
    name: Value('Uruguay'),
    japaneseName: Value('ウルグアイ'),
  ),
  const MCountryCodeCompanion(
    code: Value(186),
    name: Value('Uzbekistan'),
    japaneseName: Value('ウズベキスタン'),
  ),
  const MCountryCodeCompanion(
    code: Value(187),
    name: Value('Vanuatu'),
    japaneseName: Value('バヌアツ'),
  ),
  const MCountryCodeCompanion(
    code: Value(188),
    name: Value('Vatican City'),
    japaneseName: Value('バチカン市国'),
  ),
  const MCountryCodeCompanion(
    code: Value(189),
    name: Value('Venezuela'),
    japaneseName: Value('ベネズエラ'),
  ),
  const MCountryCodeCompanion(
    code: Value(190),
    name: Value('Vietnam'),
    japaneseName: Value('ベトナム'),
    isMajor: Value(true),
  ),
  const MCountryCodeCompanion(
    code: Value(191),
    name: Value('Yemen'),
    japaneseName: Value('イエメン'),
  ),
  const MCountryCodeCompanion(
    code: Value(192),
    name: Value('Zambia'),
    japaneseName: Value('ザンビア'),
  ),
  const MCountryCodeCompanion(
    code: Value(193),
    name: Value('Zimbabwe'),
    japaneseName: Value('ジンバブエ'),
  ),
  const MCountryCodeCompanion(
    code: Value(194),
    name: Value('Abkhazia'),
    japaneseName: Value('アブハジア'),
  ),
  const MCountryCodeCompanion(
    code: Value(195),
    name: Value('Cook Islands'),
    japaneseName: Value('クック諸島'),
  ),
  const MCountryCodeCompanion(
    code: Value(196),
    name: Value('Kosovo'),
    japaneseName: Value('コソボ'),
  ),
];
