import 'package:stairs/db/database.dart';
import 'package:drift/drift.dart';

final defaultTDevLangList = [
  const TDevLanguageCompanion(
    devLangId: Value('20479587-fddc-480b-a8e5-122190bd04f8'),
    name: Value('Angular'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('9660293d-3818-4e63-9854-db194ee81aed'),
    name: Value('Backbone'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('6889a474-3c5c-407a-b0f0-689608fe0592'),
    name: Value('Blade'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('e286e678-9c32-4a50-85e5-48aeee40f7d7'),
    name: Value('C++'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('ee1042a3-fde1-4ecc-81df-7d909926d4d0'),
    name: Value('C#'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('284e67fd-6e53-4d8a-9391-8c103392779b'),
    name: Value('Clojure'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('d263edbb-308d-421d-a633-3e04db77b3c3'),
    name: Value('CSS'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('842f9797-3615-4fa1-ad34-eef47fa88c81'),
    name: Value('Dart'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('653e339e-190e-4419-ba7b-cc0823eefadd'),
    name: Value('Django'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('b4aaa4a3-e2ae-44ae-8e43-f40234779593'),
    name: Value('Elixir'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('927ce4fc-d610-4d6f-b025-45431527998e'),
    name: Value('Ember'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('98375c8d-d4ec-469e-83c5-fed32df7abf3'),
    name: Value('Express'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('58aa380e-bde2-4b5a-955f-e6848a0a72f3'),
    name: Value('Flask'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('3020294e-4e00-47cd-b90a-b828f773c9ac'),
    name: Value('Flutter'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('c8156f5b-e086-4085-9762-2e6ea75df569'),
    name: Value('Freemarker'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('3bdff153-c42d-44f9-ad58-2f01e3b29906'),
    name: Value('Go'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('36dca736-8667-4d53-a1f5-a75512780e6e'),
    name: Value('Handlebars'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('6b817e90-38d3-4d94-876e-5b7b8f878ecb'),
    name: Value('Haskell'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('14169d52-c172-4411-82cb-9dd9c0985316'),
    name: Value('HTML'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('1e399688-9d4c-4b8e-98d7-6e02af716ab8'),
    name: Value('Java'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('c76c1cfe-6703-4777-ac46-15710f34174f'),
    name: Value('JavaScript'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('3b6be98c-7ef4-4a8b-94b9-bea2b0f0611c'),
    name: Value('Mustache'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('eee4157e-26c4-4930-befc-8f5874bd8643'),
    name: Value('Perl'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('2796388d-1eb9-4c87-83d6-e085fbebc4d9'),
    name: Value('PHP'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('3c1c9f07-5059-4673-a281-6b264b4a2ddd'),
    name: Value('Python'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('a0a62f4a-daa7-4972-827a-e43162d12b8d'),
    name: Value('R'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('0e5db70a-3e8c-405b-a27c-37135b60e173'),
    name: Value('Rails'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('8823df6c-589c-4eae-8b14-90197194881a'),
    name: Value('React'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('edea106a-1fb8-468b-999a-cf64e45fbd4b'),
    name: Value('Ruby'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('6ceca2b8-3185-4ec0-8cdf-31eb5e8d4abe'),
    name: Value('Rust'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('264ac31d-45c0-4d38-af4c-907247802aed'),
    name: Value('Sass'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('3b232d0e-5b06-41f8-a3de-3d4c2ddfbe9a'),
    name: Value('Scala'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('9c29b3b1-629d-4b4d-a775-24f82ca1de3e'),
    name: Value('Shell'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('cc38337d-21db-49cf-9506-9c1c54253170'),
    name: Value('Spring'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('46f49ebf-9afb-43c2-9265-d6bb2fb1dcf4'),
    name: Value('Spring Boot'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('08802ef5-a61a-4868-97ef-cb6eeeb620ca'),
    name: Value('Stylus'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('41efc0a2-c01b-448a-a85d-907a15e6ac04'),
    name: Value('Struts'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('19f99137-d2ce-478b-8a16-3c3c37ecca37'),
    name: Value('Swift'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('6e416cfc-18ef-45fa-a5e6-a66c5082efe9'),
    name: Value('Thymeleaf'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('f63b60bb-2dfd-4b5c-b371-f97c16746d85'),
    name: Value('TypeScript'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(false),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('7be01229-321d-46a6-8fc6-0e6e2836386b'),
    name: Value('Velocity'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  ),
  const TDevLanguageCompanion(
    devLangId: Value('22ec5cc6-ff95-4d9d-a3f3-b60707dac814'),
    name: Value('Vue'),
    accountId: Value("1"),
    isReadOnly: Value(true),
    isFramework: Value(true),
  )
];
