import 'package:drift/drift.dart';
import 'package:stairs/db/database.dart';

final defaultTagList = [
  const TTagCompanion(
    name: Value('要件定義書作成'),
    colorId: Value(1),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('要件定義書修正'),
    colorId: Value(2),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('業務フロー作成'),
    colorId: Value(3),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('業務フロー修正'),
    colorId: Value(4),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('機能仕様書作成'),
    colorId: Value(5),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('機能仕様書修正'),
    colorId: Value(6),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('画面遷移図作成'),
    colorId: Value(7),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('画面遷移図修正'),
    colorId: Value(8),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('画面レイアウト作成'),
    colorId: Value(9),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('画面レイアウト修正'),
    colorId: Value(10),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('画面設計書作成'),
    colorId: Value(11),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('画面設計書修正'),
    colorId: Value(12),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('API設計書作成'),
    colorId: Value(13),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('API設計書修正'),
    colorId: Value(14),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('帳票レイアウト作成'),
    colorId: Value(15),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('帳票レイアウト修正'),
    colorId: Value(16),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('帳票設計書作成'),
    colorId: Value(17),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('帳票設計書修正'),
    colorId: Value(18),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('テーブル設計書作成'),
    colorId: Value(19),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('テーブル設計書修正'),
    colorId: Value(20),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('ER図作成'),
    colorId: Value(21),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('ER図修正'),
    colorId: Value(22),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('新規実装'),
    colorId: Value(23),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('実装修正'),
    colorId: Value(24),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('バグ調査'),
    colorId: Value(25),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('データパッチ対応'),
    colorId: Value(26),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
  const TTagCompanion(
    name: Value('レビュー'),
    colorId: Value(27),
    isReadOnly: Value(true),
    accountId: Value('1'),
  ),
];
